#!/usr/bin/env python3
"""
Custom GRPO — 2x RTX 4090, full fine-tune (no LoRA), vLLM rollout.

Role separation
───────────────
  Rank 0  (cuda:0)  Training master
    • policy model + frozen reference model
    • AdamW optimizer, GRPO loss, mini-batch gradient update
    • reward computation (runs simulation, scores metrics)
    • W&B logging, HF checkpointing

  Rank 1  (cuda:1)  vLLM rollout worker
    • vLLM engine ONLY — no gradients, no optimizer, no W&B
    • Handles ALL generation: initial rollout AND every assistant turn
      inside the multi-turn simulation. This guarantees every turn in
      every conversation is generated by the same vLLM snapshot,
      eliminating the model-mismatch bug of mixing policy/vLLM turns.

Control protocol (5 signals, always called in identical order on both ranks)
─────────────────────────────────────────────────────────────────────────────
  CTRL_ROLLOUT    (0)  Rank 1 generates K initial completions,
                        then immediately enters the simulation sub-loop.
  CTRL_SIM_ASSIST (1)  Rank 1 generates one assistant-turn batch
                        (called once per turn level, for all active sessions).
  CTRL_SIM_DONE   (2)  Rank 1 exits the simulation sub-loop and returns
                        to the outer loop, ready for the next main signal.
  CTRL_SYNC       (3)  Rank 1 destroys and recreates the vLLM engine from
                        an HF checkpoint written by rank 0.
  CTRL_DONE       (4)  Rank 1 exits its main loop and shuts down.

Weight sync uses policy.save_pretrained() (HF format); vLLM loads from HF dirs.

DataLoader / batching
─────────────────────
  train_batch_size (B)  prompts per outer step
  K                     vLLM completions per prompt  (group size for GRPO)
  mini_batch_size  (MB) (prompt, completion) pairs per gradient sub-step

  Rewards are computed over all B×K pairs. The policy gradient update is then
  applied in MB-sized mini-batches (simple gradient accumulation over B×K/MB
  sub-steps), avoiding a single forward pass over all B×K sequences at once.

Launch
──────
  export WANDB_API_KEY="<key>"
  CUDA_VISIBLE_DEVICES=0,1 \\
  torchrun --master_port=29500 --nproc_per_node=2 -m scripts.train.grpo \\
    --dataset_repo  collabllm/collabllm-multiturn-math-hard \\
    --dataset_name  math-hard \\
    --metric_names  accuracy token_amount \\
    --metric_weights 1 -0.5 \\
    --output_dir    outputs/grpo/qwen2.5-0.5b-math \\
    --wandb_entity  <entity> --wandb_project collabllm \\
    2>&1 | tee grpo.log
"""

from __future__ import annotations

import argparse, copy, datetime, gc, hashlib, json, math, os, sys
from typing import Callable, List

import numpy as np
import torch
import torch.distributed as dist
import wandb
from dotenv import load_dotenv
from torch.utils.data import DataLoader
from transformers import AutoModelForCausalLM, AutoTokenizer
from vllm import LLM, SamplingParams

from collabllm.datasets.multiturn import MultiturnDataset
from collabllm.reward import multiturn_aware_reward        # local rewrite
from examples.single_turn_ds import datasets_info
from examples.metrics import *  # noqa: F401,F403

# Line-buffered output → `2>&1 | tee grpo.log` gets every line immediately.
sys.stdout = os.fdopen(sys.stdout.fileno(), "w", buffering=1)
sys.stderr = os.fdopen(sys.stderr.fileno(), "w", buffering=1)


# --------------------------------------------------------------------------- #
# Collective-communication helpers
# All five functions MUST be called in the same order on both ranks.
# --------------------------------------------------------------------------- #
CTRL_ROLLOUT    = 0
CTRL_SIM_ASSIST = 1
CTRL_SIM_DONE   = 2
CTRL_SYNC       = 3
CTRL_DONE       = 4


def bcast_ctrl(value: int = 0, src: int = 0) -> int:
    """Broadcast a single int from `src` to all ranks. Returns received value."""
    t = torch.tensor([value], dtype=torch.long, device="cuda")
    dist.broadcast(t, src=src)
    return int(t.item())


def bcast_obj(obj, src: int = 0):
    """Broadcast any picklable Python object from `src` to all ranks."""
    buf = [obj if dist.get_rank() == src else None]
    dist.broadcast_object_list(buf, src=src)
    return buf[0]


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser("Custom GRPO — 2x RTX 4090")

    # Data
    p.add_argument("--dataset_repo",   type=str, required=True)
    p.add_argument("--dataset_name",   type=str, required=True)
    p.add_argument("--metric_names",   nargs="+", required=True)
    p.add_argument("--metric_weights", type=float, nargs="+", default=None)
    p.add_argument("--user_generation_kwargs",   type=json.loads, default="{}")
    p.add_argument("--reward_generation_kwargs", type=json.loads, default="{}")
    p.add_argument("--max_new_turns",       type=int, default=4)
    p.add_argument("--num_samples",         type=int, default=3,
                   help="Monte-Carlo continuations per (prompt, completion) pair.")
    p.add_argument("--max_metric_workers",  type=int, default=8)
    p.add_argument("--max_sim_workers",     type=int, default=8)

    # Model
    p.add_argument("--policy_model_name", type=str,
                   default="outputs/sft/qwen2.5-0.5b-sft-math-large")
    p.add_argument("--output_dir", type=str, required=True)
    p.add_argument("--resume_ckpt_dir", type=str, default=None)

    # Training
    p.add_argument("--learning_rate",              type=float, default=2e-6)
    p.add_argument("--num_train_epochs",           type=int,   default=5)
    p.add_argument("--train_batch_size",           type=int,   default=4,
                   help="Prompts per outer training step (B).")
    p.add_argument("--mini_batch_size",            type=int,   default=2,
                   help="(prompt, completion) pairs per gradient sub-step (MB).")
    p.add_argument("--K",                          type=int,   default=4,
                   help="GRPO group size: completions sampled per prompt.")
    p.add_argument("--save_steps",                 type=int,   default=50)
    p.add_argument("--logging_steps",              type=int,   default=1)
    p.add_argument("--sync_interval",              type=int,   default=10,
                   help="Sync policy weights to vLLM every N optimizer steps.")
    p.add_argument("--kl_coeff",                   type=float, default=0.04)
    p.add_argument("--max_grad_norm",              type=float, default=1.0)
    p.add_argument("--warmup_ratio",               type=float, default=0.03)

    # Generation (shared by rollout and simulation assistant turns)
    p.add_argument("--temperature",  type=float, default=0.8)
    p.add_argument("--top_p",        type=float, default=0.9)
    p.add_argument("--max_tokens",   type=int,   default=512)
    p.add_argument("--max_model_len",type=int,   default=4096)

    # vLLM
    p.add_argument("--gpu_memory_utilization", type=float, default=0.7)

    # W&B
    p.add_argument("--wandb_project",  type=str, required=True)
    p.add_argument("--wandb_entity",   type=str, required=True)
    p.add_argument("--wandb_run_name", type=str, default=None)

    # Hub
    p.add_argument("--push_to_hub", action="store_true")
    p.add_argument("--hf_org",      type=str)

    return p.parse_args()


# --------------------------------------------------------------------------- #
# GRPO maths  (rank 0 only)
# --------------------------------------------------------------------------- #
def compute_logprobs(model: torch.nn.Module,
                     input_ids: torch.Tensor,
                     attention_mask: torch.Tensor) -> torch.Tensor:
    """Per-sequence sum of token log-probs, padding excluded. Shape: [N]."""
    logits   = model(input_ids=input_ids, attention_mask=attention_mask).logits
    logits   = logits[:, :-1]
    labels   = input_ids[:, 1:]
    lp       = torch.nn.functional.log_softmax(logits, dim=-1)
    token_lp = torch.gather(lp, -1, labels.unsqueeze(-1)).squeeze(-1)
    return (token_lp * attention_mask[:, 1:].float()).sum(-1)   # [N]


# --------------------------------------------------------------------------- #
# Reward computation  (rank 0 only)
# --------------------------------------------------------------------------- #
def make_prompt_meta_map(ds_train, tok: AutoTokenizer) -> dict:
    """rendered-prompt hash → multiturn metadata, built once before training."""
    mapping: dict = {}
    for row in ds_train:
        rp  = tok.apply_chat_template(row["prompt"], tokenize=False,
                                      add_generation_prompt=True)
        key = hashlib.md5(rp.encode()).hexdigest()
        mapping.setdefault(key, {k: row[k] for k in [
            "single_turn_prompt", "single_turn_completion",
            "single_turn_metadata", "prompt"]})
    return mapping


def make_vllm_generate_fn(sp_payload: dict) -> Callable:
    """
    Returns a closure: (batch_sessions) -> list[str]

    When called inside run_chat_simulation (for every assistant turn level),
    it signals rank 1 via CTRL_SIM_ASSIST and receives the generated replies.
    Rank 1 is already in its simulation sub-loop at this point.

    IMPORTANT: this function is NOT thread-safe. dist collectives cannot be
    called concurrently from multiple threads. Simulations must be run
    sequentially in compute_rewards (one (prompt, completion) pair at a time).
    """
    def vllm_generate_fn(batch_sessions: List[List[dict]]) -> List[str]:
        bcast_ctrl(CTRL_SIM_ASSIST)
        bcast_obj({"sessions": batch_sessions, "sp": sp_payload})
        return bcast_obj(None, src=1)
    return vllm_generate_fn


def compute_rewards(
    vllm_generate_fn: Callable,
    rendered_xK: List[str],
    completions:  List[str],
    meta_map:     dict,
    args:         argparse.Namespace,
) -> torch.Tensor:
    """
    For each (rendered_prompt, completion) pair:
      1. Look up multiturn metadata from meta_map.
      2. Call multiturn_aware_reward → runs num_samples simulations via vllm_generate_fn.
         Assistant turns in those simulations go through rank 1 (same vLLM snapshot
         that produced the initial completion), so all turns are consistent.
      3. Return mean MR as the scalar reward.

    Pairs are processed sequentially because vllm_generate_fn uses dist
    collectives (not thread-safe). Rank 1 handles the signals in its sub-loop.

    Returns float32 tensor on cuda:0, shape [B*K].
    """
    rewards = []
    for rp, comp in zip(rendered_xK, completions):
        meta = meta_map.get(hashlib.md5(rp.encode()).hexdigest())
        if meta is None:
            rewards.append(0.0)
            continue
        # Prepend the first assistant turn to start the simulation from.
        chat = meta["prompt"] + [{"role": "assistant", "content": comp}]
        info = multiturn_aware_reward(
            vllm_generate_fn,
            task_desc=datasets_info[args.dataset_name]["task_desc"],
            single_turn_prompt=meta["single_turn_prompt"],
            single_turn_completion=meta["single_turn_completion"],
            chat_history=chat,
            metadata=meta["single_turn_metadata"],
            metric_names=args.metric_names,
            metric_weights=args.metric_weights,
            user_generation_kwargs=args.user_generation_kwargs,
            reward_generation_kwargs=args.reward_generation_kwargs,
            num_samples=args.num_samples,
            max_new_turns=args.max_new_turns,
            max_metric_workers=args.max_metric_workers,
            max_sim_workers=args.max_sim_workers,
        )
        rewards.append(float(np.mean(info["MR"])))
    return torch.tensor(rewards, dtype=torch.float32, device="cuda:0")


# --------------------------------------------------------------------------- #
# Rank 0: training master
# --------------------------------------------------------------------------- #
def trainer_loop(args: argparse.Namespace) -> None:

    # ── data & tokenizer ──────────────────────────────────────────────── #
    raw_ds = MultiturnDataset(args.dataset_repo).to_inputs_dataset(eval_ratio=0.0)
    tok    = AutoTokenizer.from_pretrained(args.policy_model_name, trust_remote_code=True)
    tok.padding_side, tok.pad_token = "left", tok.eos_token

    def collate_fn(batch):
        return {k: [d[k] for d in batch] for k in batch[0]}

    train_loader = DataLoader(
        raw_ds["train"],
        batch_size=args.train_batch_size,
        shuffle=True,
        collate_fn=collate_fn,
        drop_last=True,     # keep batch size constant; avoids edge cases in grpo_loss
    )

    meta_map = make_prompt_meta_map(raw_ds["train"], tok)

    # ── models ────────────────────────────────────────────────────────── #
    policy = AutoModelForCausalLM.from_pretrained(
        args.policy_model_name, torch_dtype=torch.bfloat16,
        trust_remote_code=True).to("cuda:0")

    # Frozen reference = initial policy snapshot. Lives on cuda:0 throughout.
    ref = copy.deepcopy(policy).eval()
    for p in ref.parameters():
        p.requires_grad_(False)

    total = sum(p.numel() for p in policy.parameters())
    print(f"[rank 0] {total:,} params (all trainable) | "
          f"train set: {len(raw_ds['train']):,} samples | "
          f"batch B={args.train_batch_size} K={args.K} MB={args.mini_batch_size}")

    # ── optimizer & LR schedule ───────────────────────────────────────── #
    optimizer = torch.optim.AdamW(policy.parameters(), lr=args.learning_rate)
    total_steps   = len(train_loader) * args.num_train_epochs
    warmup_steps  = int(total_steps * args.warmup_ratio)
    def lr_lambda(s):
        if s < warmup_steps:
            return s / max(warmup_steps, 1)
        progress = (s - warmup_steps) / max(total_steps - warmup_steps, 1)
        return max(0.0, 0.5 * (1.0 + math.cos(math.pi * progress)))
    scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

    # ── vLLM sampling params (fixed; sent to rank 1 with each request) ── #
    sp_payload = {"temperature": args.temperature,
                  "top_p": args.top_p, "max_tokens": args.max_tokens}

    # ── W&B ───────────────────────────────────────────────────────────── #
    if not os.environ.get("WANDB_API_KEY"):
        print("[W&B] WANDB_API_KEY not set — run saved locally only.")
    run_name = args.wandb_run_name or (
        f"{args.dataset_repo.split('/')[-1]}"
        f"__{args.policy_model_name.rstrip('/').split('/')[-1]}"
        f"__{datetime.datetime.now().strftime('%Y%m%d-%H%M')}")
    wandb.init(project=args.wandb_project, entity=args.wandb_entity,
               name=run_name, config=vars(args),
               save_code=True, job_type="grpo-full-finetune")

    # ── training loop ─────────────────────────────────────────────────── #
    step = 0
    if args.resume_ckpt_dir:
        ckpt = torch.load(os.path.join(args.resume_ckpt_dir, "optimizer.pt"))
        optimizer.load_state_dict(ckpt["optimizer"])
        scheduler.load_state_dict(ckpt["scheduler"])
        step = ckpt["step"]

    for epoch in range(args.num_train_epochs):
        for batch in train_loader:
            step += 1
            B = args.train_batch_size

            # Render prompts to strings (Qwen chat template)
            rendered = [
                tok.apply_chat_template(p, tokenize=False, add_generation_prompt=True)
                for p in batch["prompt"]
            ]
            rendered_xK = rendered * args.K   # [B*K] — K copies per prompt

            # ── Phase 1: ROLLOUT ────────────────────────────────────────── #
            # Signal rank 1 → generate K completions per prompt.
            # After sending completions, rank 1 enters the simulation sub-loop
            # and waits for CTRL_SIM_ASSIST / CTRL_SIM_DONE signals.
            bcast_ctrl(CTRL_ROLLOUT)
            bcast_obj({"rendered_prompts": rendered_xK, "sp": sp_payload})
            completions: List[str] = bcast_obj(None, src=1)  # length B*K

            # ── Phase 2: SIMULATION + REWARDS ───────────────────────────── #
            # make_vllm_generate_fn returns a closure that sends CTRL_SIM_ASSIST
            # signals to rank 1 for every assistant turn batch.
            # Pairs are processed sequentially (dist collectives are not thread-safe).
            vllm_gen_fn = make_vllm_generate_fn(sp_payload)
            r_flat = compute_rewards(vllm_gen_fn, rendered_xK, completions,
                                     meta_map, args)

            # Signal rank 1 to exit the simulation sub-loop.
            bcast_ctrl(CTRL_SIM_DONE)

            rewards = r_flat.view(B, args.K)  # [B, K]

            # ── Phase 3: MINI-BATCH POLICY UPDATE ───────────────────────── #
            # Compute group-relative advantages once (over the full [B, K] batch).
            adv = ((rewards - rewards.mean(1, keepdim=True)) /
                   (rewards.std(1, keepdim=True) + 1e-8)).detach()   # [B, K]
            adv_flat = adv.view(-1)                                    # [B*K]

            n_mini = math.ceil(B * args.K / args.mini_batch_size)
            optimizer.zero_grad()
            total_loss = total_kl = 0.0

            policy.train()
            for mb in range(n_mini):
                s = mb * args.mini_batch_size
                e = min(s + args.mini_batch_size, B * args.K)

                enc = tok(
                    rendered_xK[s:e], completions[s:e],
                    return_tensors="pt", padding=True,
                    truncation=True, max_length=args.max_model_len
                ).to("cuda:0")

                policy_logp = compute_logprobs(
                    policy, enc["input_ids"], enc["attention_mask"])
                with torch.no_grad():
                    ref_logp = compute_logprobs(
                        ref, enc["input_ids"], enc["attention_mask"])

                kl   = policy_logp - ref_logp
                loss = -(adv_flat[s:e] * policy_logp).mean() + args.kl_coeff * kl.mean()
                (loss / n_mini).backward()   # accumulate grads across mini-batches

                total_loss += loss.item() / n_mini
                total_kl   += kl.mean().item() / n_mini

            torch.nn.utils.clip_grad_norm_(policy.parameters(), args.max_grad_norm)
            optimizer.step()
            scheduler.step()

            # ── Logging ─────────────────────────────────────────────────── #
            if step % args.logging_steps == 0:
                mr = rewards.mean().item()
                lr = scheduler.get_last_lr()[0]
                print(f"[E{epoch+1}/{args.num_train_epochs} | S{step}] "
                      f"loss={total_loss:.4f}  reward={mr:.4f}  "
                      f"kl={total_kl:.4f}  lr={lr:.2e}")
                wandb.log({"loss": total_loss, "mean_reward": mr,
                           "kl": total_kl, "lr": lr,
                           "epoch": epoch + 1}, step=step)

            # ── Weight sync to vLLM ─────────────────────────────────────── #
            if step % args.sync_interval == 0:
                sync_dir = os.path.join(args.output_dir, "_vllm_sync")
                os.makedirs(sync_dir, exist_ok=True)
                policy.save_pretrained(sync_dir)   # HF format
                tok.save_pretrained(sync_dir)
                bcast_ctrl(CTRL_SYNC)
                bcast_obj({"sync_dir": sync_dir})
                dist.barrier()   # wait until rank 1 confirms engine is reloaded
                print(f"[rank 0] vLLM sync complete at step {step}.")

            # ── Checkpoint (HF format) ───────────────────────────────────── #
            if step % args.save_steps == 0:
                ckpt = os.path.join(args.output_dir, f"step_{step}")
                policy.save_pretrained(ckpt)
                tok.save_pretrained(ckpt)
                torch.save({"optimizer": optimizer.state_dict(),
                            "scheduler": scheduler.state_dict(),
                            "step": step},
                           os.path.join(ckpt, "optimizer.pt"))
                print(f"Checkpoint saved: {ckpt}")

    # ── Shutdown rank 1 ───────────────────────────────────────────────── #
    bcast_ctrl(CTRL_DONE)

    # ── Final save (HF format) ────────────────────────────────────────── #
    policy.save_pretrained(args.output_dir)
    tok.save_pretrained(args.output_dir)
    print(f"Final model saved: {args.output_dir}")

    if args.push_to_hub and args.hf_org:
        repo = f"grpo-{args.dataset_repo.replace('/', '_')}"
        policy.push_to_hub(f"{args.hf_org}/{repo}", private=True)
        tok.push_to_hub(f"{args.hf_org}/{repo}", private=True)

    wandb.finish()


# --------------------------------------------------------------------------- #
# Rank 1: vLLM rollout worker
# --------------------------------------------------------------------------- #
def rollout_worker_loop(args: argparse.Namespace) -> None:
    """
    Inference-only process on cuda:1.
    No model weights for training, no optimizer, no W&B.

    Outer loop: waits for a main control signal.
      CTRL_ROLLOUT  → generate K initial completions
                      then enter simulation sub-loop:
                        CTRL_SIM_ASSIST → generate one assistant turn batch
                        CTRL_SIM_DONE   → exit simulation sub-loop
      CTRL_SYNC     → reload vLLM engine from HF checkpoint → barrier
      CTRL_DONE     → exit
    """
    def make_engine(model_path: str) -> LLM:
        return LLM(
            model=model_path,
            dtype="bfloat16",
            device="cuda:1",
            gpu_memory_utilization=args.gpu_memory_utilization,
            max_model_len=args.max_model_len,
            distributed_executor_backend="external_launcher",
        )

    engine = make_engine(args.policy_model_name)
    print("[rank 1] vLLM engine ready.")

    def _make_sp(sp_d: dict) -> SamplingParams:
        return SamplingParams(
            temperature=sp_d["temperature"],
            top_p=sp_d["top_p"],
            max_tokens=sp_d["max_tokens"],
        )

    while True:
        ctrl = bcast_ctrl()   # block until rank 0 sends a main signal

        if ctrl == CTRL_DONE:
            print("[rank 1] Received CTRL_DONE — shutting down.")
            break

        elif ctrl == CTRL_SYNC:
            payload  = bcast_obj(None, src=0)
            sync_dir = payload["sync_dir"]
            print(f"[rank 1] Reloading vLLM from: {sync_dir}")
            del engine; gc.collect(); torch.cuda.empty_cache()
            engine = make_engine(sync_dir)   # HF-format checkpoint
            print("[rank 1] Reload complete.")
            dist.barrier()   # signal rank 0 that engine is ready

        elif ctrl == CTRL_ROLLOUT:
            # ── Step 1: generate K initial completions ──────────────────── #
            payload     = bcast_obj(None, src=0)
            sp          = _make_sp(payload["sp"])
            outs        = engine.generate(payload["rendered_prompts"], sp,
                                          use_tqdm=False)
            completions = [o.outputs[0].text for o in outs]
            bcast_obj(completions, src=1)   # send to rank 0

            # ── Step 2: simulation sub-loop ─────────────────────────────── #
            # Rank 0 will call vllm_generate_fn (→ CTRL_SIM_ASSIST) once for
            # each assistant turn level across all active simulation sessions.
            # We stay here until rank 0 sends CTRL_SIM_DONE.
            while True:
                sub_ctrl = bcast_ctrl()

                if sub_ctrl == CTRL_SIM_DONE:
                    break   # back to outer loop, wait for next main signal

                elif sub_ctrl == CTRL_SIM_ASSIST:
                    payload   = bcast_obj(None, src=0)
                    sp        = _make_sp(payload["sp"])
                    # engine.chat handles conversational (list-of-dict) input.
                    outs      = engine.chat(payload["sessions"],
                                            sampling_params=sp, use_tqdm=False)
                    responses = [o.outputs[0].text for o in outs]
                    bcast_obj(responses, src=1)   # send to rank 0


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #
def main() -> None:
    args       = parse_args()
    local_rank = int(os.environ.get("LOCAL_RANK", "0"))
    os.makedirs(args.output_dir, exist_ok=True)

    dist.init_process_group(backend="nccl")
    torch.cuda.set_device(local_rank)
    dist.barrier()

    if local_rank == 0:
        trainer_loop(args)
    else:
        rollout_worker_loop(args)

    dist.destroy_process_group()


if __name__ == "__main__":
    load_dotenv(".env")
    main()